### ISSUE TITLE
Mention helping sources in the readme.md

### ISSUE THREAD

**Issue by rodney42** [AlCalzone/node-g-homa#1]
Hi,
it would be nice to mention the helping sources in the readme.md.

See your commit 0f6ece6eab12a91b73cafc97df1bc54273d54437:
[readme.md](https://github.com/AlCalzone/node-g-homa/commit/0f6ece6eab12a91b73cafc97df1bc54273d54437#diff-04c6e90faac2675aa89e2176d2eec7d8)
[ghoma.js](https://github.com/AlCalzone/node-g-homa/commit/0f6ece6eab12a91b73cafc97df1bc54273d54437#diff-1bef22e18e5dca320ba1c4a725a03970)

Original sources:
[FHEM](https://svn.fhem.de/trac/browser/trunk/fhem/FHEM/53_GHoma.pm)
[ghoma](https://github.com/rodney42/node-ghoma/blob/master/ghoma.js)

Best regards

**Comment by AlCalzone** [comment]
Sure, I'll do it tonight! Thanks for the reminder.
